Repository crossoverJie/JCSprout, pull requests merged in 2018-10, with the labels that each got.

#108 :sparkles: Introducing new features. #107
  pom.xml
  src/main/java/com/crossoverjie/actual/Search.java
Labels: Interview question, new features

#111 :sparkles: Introducing new features.#110
  MD/kafka/kafka-product.md
  README.md
Labels: new features

#113 notify、notifyAll书写错误
  MD/concurrent/thread-communication.md
Labels: bug

#116 :bug: Fixing a bug. #115
  src/main/java/com/crossoverjie/actual/TwoThread.java
Labels: bug

#118 Fix
  pom.xml
  src/main/java/com/crossoverjie/red/RedPacket.java
  src/test/java/com/crossoverjie/red/RedPacketTest.java
Labels: bug, enhancement
